# Site settings
title: The Great Dane
email: dan.ven@gmail.com
description: >
  A place for Dane to share his discoveries about the world as he journeys from
  being Dane, to being the Great Dane.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dvenis.github.io" # the base hostname & protocol for your site
twitter_username: uberzoonie
github_username:  dvenis

# Build settings
markdown: redcarpet
